#CC=gcc
#CC=aarch64-linux-gnu-gcc
CC=g++
DIR=dir
OBJ_DIR=obj
BIN_DIR=.
VERSION=1.0.0
TARGET=server
SRC_CPP+=server.cpp
OBJ_FILES=$(SRC_CPP:%.cpp=$(OBJ_DIR)/%.o)


CFLAGS=

LIBS=-lboost_system -lpthread
