
#some settings -> self explanatory

set shiftwidth=2
set tabstop=2
set expandtab
colorscheme elflord
set number

/usr/share/vim/vim80/defaults.vim
set mouse-=a to remove visual mode while highlighting text using mouse

#Disable Auto-comment for current session of vim
:set formatoptions-=cro
